### ISSUE TITLE
[Feature] Add logging package

### ISSUE THREAD

**Issue by felixhoffmnn** [zaanposni/vvspy#55]
**Summarize the feature**
To easier determine errors, it would be handy if a logging package would be used. For that, I recommend [Loguru](https://github.com/Delgan/loguru).

**Example of the feature**
Loguru enables the developer to just import `from loguru import logger` and then use logging levels like **debug**, **info**, and **error**. In comparison to the default logger, Loguru logs are already nicely formatted.

**Additional context**
As an alternative, the built-in logging package could be used.

**Comment by zaanposni** [comment]
Even though I like loguru - it looks really cool - I think we should rather use the pythons default logging module.
One can also edit the log format and logging level but we do not need to add another third party requirement.
