### ISSUE TITLE
[Feature] Switch from sphinx to mkdocs

### ISSUE THREAD

**Issue by felixhoffmnn** [zaanposni/vvspy#57]
**Summarize the feature**
In my opinion, Mkdocs is a more modern and easier approach to documentation in python.

Mkdocs is also compatible with [readthedocs](https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html).

**Example of the feature**
[FastAPI](https://fastapi.tiangolo.com/), [mkdocs-material](https://squidfunk.github.io/mkdocs-material/getting-started/)

**Additional context**
None

**Comment by felixhoffmnn** [comment]
@zaanposni Could you add the link (https://vvspy.readthedocs.io/en/latest/) to repository description? I think it would be a bit more convenient.

**Comment by felixhoffmnn** [comment]
When switching from sphinx to Mkdocs it would also be required to update all doc strings because they are not compatible 100% currently.

**Comment by zaanposni** [comment]
I agree that mkdocs looks more modern and should be used.
I have added the link to the repository description.

> When switching from sphinx to Mkdocs it would also be required to update all doc strings because they are not compatible 100% currently.

Would be good to review/rework those doc strings anyway 😄

**Comment by zaanposni** [comment]
@felixhoffmnn do you want to work on this issue?
In the meantime I could look into #55

**Comment by felixhoffmnn** [comment]
Sounds good. Yeah, you can assign me :smiley: 

I was slightly over-motivated and started working on #55, #56, and #57. You can look through the current progress here: https://github.com/felixhoffmnn/vvspy. If there appears anything that is not wanted or not in this project's scope, please comment on the regarding commit.

**Comment by zaanposni** [comment]
Hi @felixhoffmnn as you may have guessed I am currently a bit busy ^.^
I plan to get back to this project next weekend at the latest.

The only thing I dont like is the use of jupyter notebooks as examples and the new logging framework as those things introduce unnecessary third party dependencies.

I would have to go through your changes more carefully once you feel like they are ready to review. Maybe you should split them up in smaller PRs too ^.^

**Comment by zaanposni** [comment]
Again, I can work on issues too if you want me to. No need to do everything on your own.

**Comment by zaanposni** [comment]
wont be fixed for now
