### ISSUE TITLE
[Feature] Add more tests

### ISSUE THREAD

**Issue by felixhoffmnn** [zaanposni/vvspy#58]
**Summarize the feature**
Currently, this project's test coverage is only 60%. Especially `get_depatures()`, `get_trips`, and `get_arrivals()` needs to be tested. Additionally, all the data classes should be tested as well.

**Example of the feature**
None

**Additional context**
None

**Comment by zaanposni** [comment]
There have been calculation issues in the past that should be addressed in a test too, see: #52

**Comment by zaanposni** [comment]
wont be fixed for now
