### ISSUE TITLE
[Feature] Add Codecov Reports

### ISSUE THREAD

**Issue by felixhoffmnn** [zaanposni/vvspy#60]
**Summarize the feature**
To ensure the functionality, the test coverage should be at least 80%. I recommend using [Codecov](https://about.codecov.io/).

**Additional context**
Using `pytest`, `pytest-cov`, and GitHub Actions, this can be easily achieved. An example configuration can be found [here](https://github.com/felixhoffmnn/python_template/blob/main/.github/workflows/codecov.yaml).

**Comment by zaanposni** [comment]
wont be fixed for now
